//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P7.AspNetCore.Authentication.OpenIdConnect {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("P7.AspNetCore.Authentication.OpenIdConnect.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot process the message. Both id_token and code are missing..
        /// </summary>
        internal static string IdTokenCodeMissing {
            get {
                return ResourceManager.GetString("IdTokenCodeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message contains error: &apos;{0}&apos;, error_description: &apos;{1}&apos;, error_uri: &apos;{2}&apos;..
        /// </summary>
        internal static string MessageContainsError {
            get {
                return ResourceManager.GetString("MessageContainsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to unprotect the message.State..
        /// </summary>
        internal static string MessageStateIsInvalid {
            get {
                return ResourceManager.GetString("MessageStateIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenIdConnectAuthenticationHandler: message.State is null or empty..
        /// </summary>
        internal static string MessageStateIsNullOrEmpty {
            get {
                return ResourceManager.GetString("MessageStateIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to validate the &apos;id_token&apos;, no suitable ISecurityTokenValidator was found for: &apos;{0}&apos;.&quot;.
        /// </summary>
        internal static string UnableToValidateToken {
            get {
                return ResourceManager.GetString("UnableToValidateToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Validated Security Token must be of type JwtSecurityToken, but instead its type is: &apos;{0}&apos;..
        /// </summary>
        internal static string ValidatedSecurityTokenNotJwt {
            get {
                return ResourceManager.GetString("ValidatedSecurityTokenNotJwt", resourceCulture);
            }
        }
    }
}
